version: '3.4'

services:
  place:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    environment:
      ENV: dev
    ports:
      - $REST_PORT:$REST_PORT
    volumes:
      - .:/go/src/
    depends_on:
      - postgres
    networks:
      - place
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'

  postgres:
    image: postgres:9.4
    restart: always
    tty: true
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - $DB_PORT:5432
    networks:
      - place

  pgadmin:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - place

volumes:
  pgdata:
    driver: local

networks:
  place:
    driver: bridge
