apiVersion: v1
kind: Service
metadata:
  name: place
  labels:
    app: place
    service: place
spec:
  type: ClusterIP
  selector:
    app: place
  ports:
  - name: rest
    port: 8080
    targetPort: 8080
